import Head from "next/head";
import Banner from "../components/banner";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Card from "../components/card";
import coffeeStoresData from "../data/5.1 coffee-stores.json";
import { fetchCoffeeStores } from "../lib/coffee-stores";

export async function getStaticProps(context) {
  const coffeeStores = await fetchCoffeeStores();

  // .catch((err) => console.error(err));
  return {
    props: { coffeeStores }, // will be passed to the page component as props
  };
}
export default function Home(props) {
  function handleOnBannerBtnClick() {
    console.log("Hi banner button");
  }
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          handleOnClick={handleOnBannerBtnClick}
          buttonText="View stores nearby"
        />
        <div className={styles.coffeeImg}>
          <Image src="/static/coffee.png" width={500} height={250} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>)
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((element) => {
                return (
                  <Card
                    key={element.fsq_id}
                    name={element.name}
                    imgUrl={element.imgUrl}
                    href={`/coffee-store/${element.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </>
  );
}
